<?php /* Smarty version Smarty-3.1.19, created on 2014-08-08 19:57:20
         compiled from "C:\xampp\htdocs\Tassel\admin\themes\default\css\overrides.css" */ ?>
<?php /*%%SmartyHeaderCode:2135953e50f80161103-23618721%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '2efe64024dbc13189e23dd1dd1234550b8f5eb1a' => 
    array (
      0 => 'C:\\xampp\\htdocs\\Tassel\\admin\\themes\\default\\css\\overrides.css',
      1 => 1407520286,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '2135953e50f80161103-23618721',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.19',
  'unifunc' => 'content_53e50f801641b1_03077872',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_53e50f801641b1_03077872')) {function content_53e50f801641b1_03077872($_smarty_tpl) {?>/* This stylesheet should be used to add your custom styles to the back-office without using the Sass sources. It will be loaded after all the default styles. 
You should NOT edit any other exisiting back-office CSS file manually: they are generated by the Sass preprocessor: http://www.sass-lang.com/ . */<?php }} ?>
